#!/usr/bin/env python3
"""Convert 1-bpp BMP images to the Pervasive Displays frame format.

The 2.7" panel stores a frame as PV_EINK_IMAGE_SIZE bytes: 264/8 = 33 bytes
per row, 176 rows, no row padding, MSB = leftmost pixel, one bit per pixel
with 1 = white and 0 = black.

A 1-bpp BMP holds the same pixels but with two differences that this tool
removes:

  * rows are padded to a 4-byte boundary (33 -> 36 bytes);
  * rows are stored bottom-up for a positive biHeight (the usual case), while
    the panel wants row 0 at the top.

The BMP palette is expected to be index 0 = black, index 1 = white, which is
what a normal monochrome BMP writes, after which the bit values can be copied
through unchanged: BMP bit 1 = white = the panel's 0xFF byte.

Usage:
    python bmp_to_eink.py <in.bmp> [<in2.bmp> ...] --out <resource.c> \
                          [--prefix board_] [--flip-y] [--invert]

    python bmp_to_eink.py ../eink_assets/board_0.bmp \
                          ../eink_assets/board_1.bmp \
                          --out ../src/resource.c --prefix board_

Options:
    --flip-y   flip rows after the BMP bottom-up conversion. Use this if the
               image renders upside down on the panel.
    --invert   invert black/white. Use this if the image renders as a
               negative (i.e. the BMP palette was not index 0 = black).

Pure standard library.
"""

import argparse
import os
import struct
import sys

ROW_BYTES = 33          # 264 / 8
ROWS = 176
IMAGE_SIZE = ROW_BYTES * ROWS   # 5808


def read_bmp_1bpp(path):
    """Return (width, height, rows) with rows top-down, unpacked to 33 B/row."""
    data = open(path, "rb").read()

    if data[:2] != b"BM":
        raise SystemExit("%s: not a BMP (signature %r)" % (path, data[:2]))

    data_off = struct.unpack("<I", data[10:14])[0]
    hdr_size = struct.unpack("<I", data[14:18])[0]
    width = struct.unpack("<i", data[18:22])[0]
    height = struct.unpack("<i", data[22:26])[0]
    planes = struct.unpack("<H", data[26:28])[0]
    bpp = struct.unpack("<H", data[28:30])[0]
    compression = struct.unpack("<I", data[30:34])[0]

    if hdr_size < 40:
        raise SystemExit("%s: unsupported DIB header size %d" % (path, hdr_size))
    if planes != 1 or bpp != 1 or compression != 0:
        raise SystemExit(
            "%s: expected an uncompressed 1-bpp BMP, got bpp=%d planes=%d comp=%d"
            % (path, bpp, planes, compression))
    if width != ROW_BYTES * 8 or abs(height) != ROWS:
        raise SystemExit(
            "%s: expected %dx%d, got %dx%d"
            % (path, ROW_BYTES * 8, ROWS, width, abs(height)))

    bottom_up = height > 0
    row_stride = ((width + 31) // 32) * 4

    rows = []
    for r in range(abs(height)):
        start = data_off + r * row_stride
        rows.append(data[start:start + ROW_BYTES])

    if bottom_up:
        rows.reverse()

    return width, abs(height), rows


def emit_c(entries, out_path, prefix):
    """Write a resource .c / .h pair. `entries` is [(name, bytes), ...]."""
    base = os.path.splitext(os.path.basename(out_path))[0]
    header_name = base + ".h"

    with open(out_path, "w") as f:
        f.write("/*\n")
        f.write("  %s - generated by tools/bmp_to_eink.py, DO NOT EDIT BY HAND.\n"
                % os.path.basename(out_path))
        f.write("\n")
        f.write("  Pervasive Displays 2.7\" frame format: %d x %d, 1 bpp,\n"
                % (ROW_BYTES * 8, ROWS))
        f.write("  %d bytes per row (no padding), MSB = leftmost pixel,\n"
                % ROW_BYTES)
        f.write("  1 = white, 0 = black, top-down.\n")
        f.write("  Regenerate with tools/bmp_to_eink.py rather than editing.\n")
        f.write("*/\n\n")
        f.write('#include "%s"\n\n' % header_name)

        for name, payload in entries:
            assert len(payload) == IMAGE_SIZE, len(payload)
            f.write("const uint8_t %s[PV_EINK_IMAGE_SIZE] =\n{\n" % name)
            for i in range(0, IMAGE_SIZE, 16):
                chunk = payload[i:i + 16]
                f.write("    " + ",".join("0x%02X" % b for b in chunk) + ",\n")
            f.write("};\n\n")

    hdr_path = os.path.join(os.path.dirname(out_path) or ".", header_name)
    with open(hdr_path, "w") as f:
        f.write("/*\n")
        f.write("  %s - generated by tools/bmp_to_eink.py, DO NOT EDIT BY HAND.\n"
                % header_name)
        f.write("*/\n\n")
        f.write("#ifndef %s_INCLUDED\n" % base.upper())
        f.write("#define %s_INCLUDED\n\n" % base.upper())
        f.write('#include <stdint.h>\n')
        f.write('#include "pervasive_eink_configuration.h"\n\n')
        for name, _ in entries:
            f.write("extern const uint8_t %s[PV_EINK_IMAGE_SIZE];\n" % name)
        f.write("\n#endif /* %s_INCLUDED */\n" % base.upper())

    print("wrote %s and %s" % (out_path, hdr_path))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+", help="1-bpp BMP file(s)")
    ap.add_argument("--out", required=True, help="output .c file")
    ap.add_argument("--prefix", default="", help="symbol name prefix")
    ap.add_argument("--flip-y", action="store_true",
                    help="flip rows after the bottom-up conversion")
    ap.add_argument("--invert", action="store_true",
                    help="invert black/white")
    args = ap.parse_args()

    entries = []
    for path in args.inputs:
        w, h, rows = read_bmp_1bpp(path)
        if args.flip_y:
            rows = list(reversed(rows))
        payload = bytearray()
        for row in rows:
            payload += bytes(0xFF ^ b for b in row) if args.invert else row
        name = args.prefix + os.path.splitext(os.path.basename(path))[0]
        name = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
        entries.append((name, bytes(payload)))
        white = sum(bin(b).count("1") for b in payload)
        print("%s: %dx%d, %.1f%% white pixels"
              % (path, w, h, 100.0 * white / (w * h)))

    emit_c(entries, args.out, args.prefix)


if __name__ == "__main__":
    sys.exit(main())
