/*
  resource.h - generated by tools/bmp_to_eink.py, DO NOT EDIT BY HAND.
*/

#ifndef RESOURCE_INCLUDED
#define RESOURCE_INCLUDED

#include <stdint.h>
#include "pervasive_eink_configuration.h"

extern const uint8_t board_0[PV_EINK_IMAGE_SIZE];
extern const uint8_t board_1[PV_EINK_IMAGE_SIZE];

#endif /* RESOURCE_INCLUDED */
